import { useEffect, useMemo, useState } from 'react';
import { Activity, Check, ChevronDown, ChevronLeft, ChevronRight, Download, FolderKanban, MoreHorizontal, Search, SlidersHorizontal, X } from 'lucide-react';
import './DataPage.css';

const money = (value: unknown) => new Intl.NumberFormat('es-GT', { style: 'currency', currency: 'GTQ' }).format(Number(value || 0));
const columns: Record<string, [string, string][]> = {
  products: [['sku','SKU'],['name','Producto'],['category.name','Categoría'],['salePrice','Precio venta'],['inventory','Stock']],
  inventory: [['product.name','Producto'],['branch.name','Sucursal'],['quantity','Existencias'],['product.minStock','Mínimo']],
  wood: [['product.name','Madera'],['woodType','Tipo'],['dimensions','Medida'],['product.inventory','Stock']],
  sales: [['number','No. venta'],['customer.name','Cliente'],['total','Total'],['paid','Pagado'],['status','Estado'],['createdAt','Fecha']],
  purchases: [['number','No. compra'],['supplier.name','Proveedor'],['total','Total'],['paid','Pagado'],['status','Estado'],['createdAt','Fecha']],
  customers: [['name','Cliente'],['company','Empresa'],['nit','NIT'],['phone','Teléfono'],['email','Correo']],
  suppliers: [['name','Proveedor'],['company','Empresa'],['nit','NIT'],['phone','Teléfono'],['email','Correo']],
  deliveries: [['number','Entrega'],['customer.name','Cliente'],['address','Dirección'],['driver.user.name','Camionero'],['status','Estado']],
  branches: [['name','Sucursal'],['code','Código'],['address','Dirección'],['phone','Teléfono'],['active','Estado']],
  cash: [['branch.name','Sucursal'],['opening','Apertura'],['expected','Esperado'],['closedAt','Cierre'],['openedAt','Fecha']],
  expenses: [['category','Categoría'],['description','Descripción'],['amount','Monto'],['method','Método'],['createdAt','Fecha']],
  movements: [['product.name','Producto'],['branch.name','Sucursal'],['type','Movimiento'],['quantity','Cantidad'],['createdAt','Fecha']],
  users: [['name','Usuario'],['username','Nombre de usuario'],['role.name','Rol'],['branch.name','Sucursal'],['active','Estado']],
  drivers: [['user.name','Camionero'],['user.username','Usuario'],['phone','Teléfono'],['licenseNumber','Licencia'],['plate','Placa'],['user.active','Estado']],
  routes: [['name','Ruta'],['date','Fecha'],['driver.user.name','Camionero'],['deliveries','Entregas'],['status','Estado']],
  transfers: [['number','No. traslado'],['origin.name','Origen'],['destination.name','Destino'],['status','Estado'],['createdAt','Fecha']],
  audit: [['action','Acción'],['module','Módulo'],['user.name','Usuario'],['recordId','Registro'],['createdAt','Fecha']],
};
const endpoint: Record<string,string> = { products:'/products',inventory:'/inventory',wood:'/wood',sales:'/sales',purchases:'/purchases',transfers:'/transfers',customers:'/customers',suppliers:'/suppliers',drivers:'/drivers',deliveries:'/deliveries',routes:'/routes',branches:'/branches',cash:'/cash',expenses:'/expenses',movements:'/movements',users:'/users',audit:'/audit',reports:'/reports/summary' };
const get = (obj:any,path:string) => path.split('.').reduce((v,k)=>v?.[k],obj);
function unwrap(page:string, result:any) { if (Array.isArray(result)) return { rows:result,total:result.length }; if(page==='reports') return { rows:result.sales||[],total:(result.sales||[]).length }; return { rows:result.data||result.rows||[],total:Number(result.total||0) }; }
function csvValue(value:any) { let text=String(value??''); if (/^[\s]*[=+@-]/.test(text)) text="'"+text; return `"${text.replace(/"/g,'""')}"`; }
function exportCsv(rows:any[], cols:[string,string][], filename:string) {
  if (!rows.length) return;
  const csv='\uFEFF'+[cols.map(([,label])=>csvValue(label)).join(','),...rows.map(row=>cols.map(([key])=>{const value=get(row,key);return csvValue(value&&typeof value==='object'?Array.isArray(value)?value.map((x:any)=>`${x.branch?.name||''}: ${x.quantity}`).join(' | '):JSON.stringify(value):value)}).join(','))].join('\r\n');
  const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'})); const a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
}

export default function DataPage({page,rows,busy,onRefresh,api,user,setError,setSuccess,branchId}:any) {
  const [items,setItems]=useState<any[]>(rows||[]); const [total,setTotal]=useState(0); const [pageNo,setPageNo]=useState(1); const [pageSize,setPageSize]=useState(20);
  const [search,setSearch]=useState(''); const [filter,setFilter]=useState(''); const [sort,setSort]=useState(''); const [descending,setDescending]=useState(false);
  const [selected,setSelected]=useState<Set<string>>(new Set()); const [menu,setMenu]=useState<string|null>(null); const [details,setDetails]=useState<any|null>(null); const [editing,setEditing]=useState<any|null>(null); const [payment,setPayment]=useState<any|null>(null); const [saleReturn,setSaleReturn]=useState<any|null>(null); const [adjustment,setAdjustment]=useState<any|null>(null); const [closing,setClosing]=useState<any|null>(null); const [actionBusy,setActionBusy]=useState(false);
  const [company,setCompany]=useState<any>(null);
  useEffect(()=>{setItems(rows||[]);setTotal(0);setPageNo(1);setSelected(new Set());},[rows,page]);
  useEffect(()=>{if(page==='settings')api('/settings').then(setCompany).catch((e:any)=>setError(e.message));},[page]);
  const cols=columns[page]||[['name','Nombre'],['createdAt','Fecha']];
  const visible=useMemo(()=>{let list=items.filter(row=>{const text=search.toLowerCase();const matches=!text||cols.some(([key])=>String(get(row,key)??'').toLowerCase().includes(text));const state=filter==='active'?row.active!==false:filter==='inactive'?row.active===false:filter?row.status===filter:true;return matches&&state});if(sort)list=[...list].sort((a,b)=>String(get(a,sort)??'').localeCompare(String(get(b,sort)??''),undefined,{numeric:true,sensitivity:'base'})*(descending?-1:1));return list;},[items,search,filter,sort,descending,page]);
  if(page==='backups') return <BackupTools api={api} rows={rows} onRefresh={onRefresh} setError={setError} setSuccess={setSuccess}/>;
  if(page==='settings') return <SettingsPanel api={api} company={company} setCompany={setCompany} setError={setError} setSuccess={setSuccess}/>;
  async function changePage(next:number,size=pageSize){if(next<1)return;try{const params=new URLSearchParams({page:String(next),limit:String(size)});if(branchId)params.set('branchId',branchId);const result=await api(`${endpoint[page]}?${params}`);const pageData=unwrap(page,result);if(next>1&&!pageData.rows.length)return;setItems(pageData.rows);setTotal(pageData.total);setPageNo(next);setSelected(new Set());}catch(e:any){setError(e.message)}}
  function openPayment(row:any,type:string){setPayment({id:row.id,type,amount:'',method:'EFECTIVO',note:''});setMenu(null)}
  async function runStatus(row:any,status:string){try{await api(`/deliveries/${row.id}/status`,{method:'PATCH',body:JSON.stringify({status})});setSuccess(`Entrega actualizada: ${status}.`);setMenu(null);onRefresh()}catch(e:any){setError(e.message)}}
  async function setActive(row:any){const active=page==='drivers'?row.user?.active!==false:row.active!==false;try{await api(`/${page}/${row.id}`,{method:'PATCH',body:JSON.stringify({active:!active})});setSuccess(active?'Registro desactivado.':'Registro activado.');setMenu(null);onRefresh()}catch(e:any){setError(e.message)}}
  async function saveEdit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const payload=Object.fromEntries(new FormData(event.currentTarget).entries());try{setActionBusy(true);await api(`/${page}/${editing.id}`,{method:'PATCH',body:JSON.stringify(payload)});setSuccess('Cambios guardados.');setEditing(null);onRefresh()}catch(e:any){setError(e.message)}finally{setActionBusy(false)}}
  async function submitPayment(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(!payment)return;const path=payment.type==='sale'?`/sales/${payment.id}/payments`:`/purchases/${payment.id}/payments`;try{setActionBusy(true);await api(path,{method:'POST',body:JSON.stringify({amount:Number(payment.amount),method:payment.method,note:payment.note||undefined})});setSuccess(payment.type==='sale'?'Abono de cliente registrado.':'Pago a proveedor registrado.');setPayment(null);onRefresh()}catch(e:any){setError(e.message)}finally{setActionBusy(false)}}
  function openReturn(row:any){const returned=new Map<string,number>();for(const ret of row.returns||[])for(const line of ret.items||[])returned.set(line.saleItemId,(returned.get(line.saleItemId)||0)+Number(line.quantity));setSaleReturn({row,reason:'',items:(row.items||[]).map((item:any)=>({...item,remaining:Math.max(0,Number(item.quantity)-(returned.get(item.id)||0)),quantity:0}))})}
  async function submitReturn(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(!saleReturn)return;const items=saleReturn.items.filter((x:any)=>Number(x.quantity)>0).map((x:any)=>({saleItemId:x.id,quantity:Number(x.quantity)}));if(!items.length){setError('Indica la cantidad que se devolverá.');return}try{setActionBusy(true);await api(`/sales/${saleReturn.row.id}/returns`,{method:'POST',body:JSON.stringify({reason:saleReturn.reason,items})});setSuccess('Devolución registrada; se actualizó el inventario y el saldo.');setSaleReturn(null);onRefresh()}catch(e:any){setError(e.message)}finally{setActionBusy(false)}}
  async function submitAdjustment(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(!adjustment)return;const fd=new FormData(event.currentTarget);try{setActionBusy(true);await api('/inventory/adjust',{method:'POST',body:JSON.stringify({productId:adjustment.productId||adjustment.product?.id,branchId:adjustment.branchId||adjustment.branch?.id,quantity:Number(fd.get('quantity')),reason:fd.get('reason')})});setSuccess('Inventario actualizado y movimiento registrado.');setAdjustment(null);onRefresh()}catch(e:any){setError(e.message)}finally{setActionBusy(false)}}
  async function closeCash(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(!closing)return;const fd=new FormData(event.currentTarget);try{setActionBusy(true);await api(`/cash/${closing.id}/close`,{method:'POST',body:JSON.stringify({counted:Number(fd.get('counted')),notes:fd.get('notes')})});setSuccess('Caja cerrada correctamente.');setClosing(null);onRefresh()}catch(e:any){setError(e.message)}finally{setActionBusy(false)}}
  async function cancelDocument(row:any){const reason=window.prompt('Escribe el motivo de anulación:');if(!reason?.trim())return;try{await api(`/${page}/${row.id}/cancel`,{method:'POST',body:JSON.stringify({reason})});setSuccess('Documento anulado y existencias conciliadas.');setMenu(null);onRefresh()}catch(e:any){setError(e.message)}}
  async function changeStatus(row:any,status:string){if(page==='deliveries')return runStatus(row,status);try{await api(`/transfers/${row.id}/receive`,{method:'POST'});setSuccess('Traslado recibido e inventario actualizado.');setMenu(null);onRefresh()}catch(e:any){setError(e.message)}}
  async function menuAction(action:string,row:any){setMenu(null);if(action==='details')return setDetails(row);if(action==='edit')return setEditing(row);if(action==='deactivate'||action==='activate')return setActive(row);if(action==='adjust')return setAdjustment(row);if(action==='pay-sale')return openPayment(row,'sale');if(action==='pay-purchase')return openPayment(row,'purchase');if(action==='return')return openReturn(row);if(action==='close-cash')return setClosing(row);if(action==='cancel')return cancelDocument(row);if(action==='in-transit')return runStatus(row,'EN_CAMINO');if(action==='delivered')return runStatus(row,'ENTREGADA');if(action==='not-delivered')return runStatus(row,'NO_ENTREGADA');if(action==='cancel-delivery')return runStatus(row,'CANCELADA');if(action==='receive-transfer')return changeStatus(row,'RECIBIDO');}
  function actionsFor(row:any){const a:[string,string][]=[['details','Ver detalles']];if(['products','customers','suppliers','branches','users','drivers'].includes(page)){const active=page==='drivers'?row.user?.active!==false:row.active!==false;a.push(['edit','Editar'],[active?'deactivate':'activate',active?'Desactivar':'Activar']);}if(page==='inventory'||page==='products')a.push(['adjust','Ajustar existencias']);if(page==='sales'&&row.status!=='ANULADA'){if(Number(row.total)>Number(row.paid||0))a.push(['pay-sale','Registrar abono']);a.push(['return','Registrar devolución'],['cancel','Anular venta']);}if(page==='purchases'&&row.status!=='ANULADA'){if(Number(row.total)>Number(row.paid||0))a.push(['pay-purchase','Registrar pago']);a.push(['cancel','Anular compra']);}if(page==='deliveries'&&user?.role!=='CAMIONERO'){if(row.status==='PENDIENTE')a.push(['in-transit','Iniciar entrega']);if(row.status==='ASIGNADA')a.push(['in-transit','Marcar en camino']);if(row.status==='EN_CAMINO')a.push(['delivered','Marcar entregada'],['not-delivered','No entregada']);if(!['ENTREGADA','CANCELADA'].includes(row.status))a.push(['cancel-delivery','Cancelar entrega']);}if(page==='deliveries'&&user?.role==='CAMIONERO'){if(row.status==='ASIGNADA')a.push(['in-transit','Iniciar ruta']);if(row.status==='EN_CAMINO')a.push(['delivered','Marcar entregada'],['not-delivered','No entregada']);}if(page==='cash'&&!row.closedAt)a.push(['close-cash','Cerrar caja']);if(page==='transfers'&&row.status==='ENVIADO')a.push(['receive-transfer','Recibir traslado']);return a;}
  function onSelect(id:string,checked:boolean){setSelected(prev=>{const next=new Set(prev);checked?next.add(id):next.delete(id);return next})}
  const statuses=['PENDIENTE','ASIGNADA','EN_CAMINO','ENTREGADA','NO_ENTREGADA','CANCELADA','PARCIAL','PAGADA','RECIBIDO'];
  return <section className="panel table-panel">
    <div className="table-toolbar"><div><h3>{pageLabel(page)}</h3><p>{busy?'Cargando registros…':`${total||items.length} registros encontrados`}</p></div><div className="table-tools"><div className="table-search"><Search size={15}/><input aria-label="Buscar en esta tabla" placeholder="Buscar registros..." value={search} onChange={e=>setSearch(e.target.value)}/></div><button className="filter-button" onClick={()=>setFilter(v=>v?'':'active')} title="Mostrar filtros"><SlidersHorizontal size={14}/>{filter==='active'?'Activos':'Filtros'}</button><button className="secondary" onClick={()=>exportCsv(visible,cols,`${page}.csv`)} disabled={!visible.length}><Download size={14}/> CSV</button><button className="icon-button subtle" title="Actualizar" onClick={onRefresh}><Activity size={16}/></button></div></div>
    {filter&&<div className="table-toolbar"><label>Estado<select aria-label="Filtrar estado" value={filter} onChange={e=>setFilter(e.target.value)}><option value="">Todos</option><option value="active">Activos</option><option value="inactive">Inactivos</option>{statuses.map(s=><option value={s} key={s}>{s}</option>)}</select></label></div>}
    {page==='reports'&&<div className="report-summary"><div><span>Ventas listadas</span><b>{money(items.reduce((n:number,x:any)=>n+Number(x.total||0),0))}</b></div><div><span>Documentos</span><b>{items.length}</b></div></div>}
    {selected.size>0&&<div className="table-toolbar"><span>{selected.size} registros seleccionados</span><button className="secondary" onClick={()=>{const chosen=visible.filter(x=>selected.has(x.id));exportCsv(chosen,cols,`${page}-seleccion.csv`)}}><Download size={14}/> Exportar selección</button><button className="secondary" onClick={()=>setSelected(new Set())}>Quitar selección</button></div>}
    <div className="table-scroll"><table><thead><tr><th className="check-cell"><input aria-label="Seleccionar todos" type="checkbox" checked={visible.length>0&&visible.every(x=>selected.has(x.id))} onChange={e=>setSelected(e.target.checked?new Set(visible.map(x=>x.id)):new Set())}/></th>{cols.map(([key,label])=><th key={key}><button className="table-sort" onClick={()=>{setDescending(sort===key?!descending:false);setSort(key)}}>{label}<ChevronDown size={12}/></button></th>)}<th>Acciones</th></tr></thead><tbody>{visible.map((row:any,i:number)=><tr key={row.id||i}><td className="check-cell"><input aria-label={`Seleccionar ${row.name||row.number||i+1}`} type="checkbox" checked={selected.has(row.id)} onChange={e=>onSelect(row.id,e.target.checked)}/></td>{cols.map(([key])=>{const value=get(row,key);return <td key={key}>{['total','paid','salePrice','purchasePrice','amount','opening','expected'].includes(key)?money(value):['createdAt','openedAt','closedAt','date'].includes(key)?value?new Date(value).toLocaleDateString('es-GT'):'—':key==='inventory'||key==='product.inventory'?Array.isArray(value)?value.map((x:any)=>`${x.branch?.name}: ${x.quantity}`).join(' · '):'—':key==='deliveries'?Array.isArray(value)?`${value.length} asignadas`:'—':key==='active'||key==='user.active'?<span className={`badge ${value?'success':'muted'}`}>{value?'Activo':'Inactivo'}</span>:key==='status'?<span className={`badge ${['ENTREGADA','PAGADA','RECIBIDO'].includes(value)?'success':['PENDIENTE','ASIGNADA','PARCIAL','EN_CAMINO'].includes(value)?'warning':'muted'}`}>{value}</span>:value||'—'}</td>})}<td className="row-actions"><button className="icon-button row-action" title="Acciones del registro" aria-label="Acciones del registro" onClick={()=>setMenu(menu===row.id?null:row.id)}><MoreHorizontal size={17}/></button>{menu===row.id&&<div className="row-action-menu">{actionsFor(row).map(([action,label])=><button key={action} onClick={()=>menuAction(action,row)}>{label}</button>)}</div>}</td></tr>)}</tbody></table>{!visible.length&&<div className="empty-state"><div><FolderKanban size={23}/></div><b>{busy?'Cargando datos…':'Aún no hay registros'}</b><span>{search?'No hay resultados que coincidan con la búsqueda.':'Cuando agregues información, aparecerá aquí.'}</span></div>}</div>
    <div className="table-bottom"><span>Mostrando <b>{visible.length?((pageNo-1)*pageSize+1):0}–{(pageNo-1)*pageSize+visible.length}</b> de <b>{total||items.length}</b> resultados</span><div><button aria-label="Página anterior" disabled={pageNo<=1} onClick={()=>changePage(pageNo-1)}><ChevronLeft size={15}/></button><button className="page-number">{pageNo}</button><button aria-label="Página siguiente" disabled={items.length<pageSize} onClick={()=>changePage(pageNo+1)}><ChevronRight size={15}/></button></div><select aria-label="Registros por página" value={pageSize} onChange={e=>{const n=Number(e.target.value);setPageSize(n);changePage(1,n)}}><option value={20}>20 por página</option><option value={50}>50 por página</option><option value={100}>100 por página</option></select></div>
    {details&&<div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setDetails(null)}><div className="modal"><div className="modal-head"><div><span className="eyebrow">DETALLE DEL REGISTRO</span><h2>{details.name||details.number||details.sku||pageLabel(page)}</h2></div><button className="icon-button" onClick={()=>setDetails(null)}><X size={18}/></button></div><pre className="record-details">{JSON.stringify(details,null,2)}</pre><div className="modal-actions"><button className="primary" onClick={()=>setDetails(null)}>Cerrar</button></div></div></div>}
    {editing&&<div className="modal-backdrop"><form className="modal" onSubmit={saveEdit}><div className="modal-head"><div><span className="eyebrow">EDICIÓN</span><h2>Editar registro</h2></div><button type="button" className="icon-button" onClick={()=>setEditing(null)}><X size={18}/></button></div><div className="form-grid">{editFields(page,editing).map(([key,label,type])=><label key={key}>{label}<input name={key} type={type||'text'} defaultValue={editing[key]??''}/></label>)}</div><div className="modal-actions"><button type="button" className="secondary" onClick={()=>setEditing(null)}>Cancelar</button><button className="primary" disabled={actionBusy}>{actionBusy?'Guardando…':'Guardar cambios'}</button></div></form></div>}
    {payment&&<div className="modal-backdrop"><form className="modal" onSubmit={submitPayment}><div className="modal-head"><div><span className="eyebrow">CUENTA PENDIENTE</span><h2>{payment.type==='sale'?'Registrar abono':'Registrar pago'}</h2></div><button type="button" className="icon-button" onClick={()=>setPayment(null)}><X size={18}/></button></div><div className="form-grid"><label>Monto<input required name="amount" type="number" min="0.01" step="0.01" value={payment.amount} onChange={e=>setPayment({...payment,amount:e.target.value})}/></label><label>Método<select value={payment.method} onChange={e=>setPayment({...payment,method:e.target.value})}><option value="EFECTIVO">Efectivo</option><option value="TARJETA">Tarjeta</option><option value="TRANSFERENCIA">Transferencia</option></select></label><label className="wide">Observación<input value={payment.note} onChange={e=>setPayment({...payment,note:e.target.value})}/></label></div><div className="modal-actions"><button type="button" className="secondary" onClick={()=>setPayment(null)}>Cancelar</button><button className="primary" disabled={actionBusy}>{actionBusy?'Guardando…':'Registrar pago'}</button></div></form></div>}
    {adjustment&&<div className="modal-backdrop"><form className="modal" onSubmit={submitAdjustment}><div className="modal-head"><div><span className="eyebrow">MOVIMIENTO AUDITADO</span><h2>Ajustar inventario</h2></div><button type="button" className="icon-button" onClick={()=>setAdjustment(null)}><X size={18}/></button></div><p>{adjustment.product?.name||adjustment.name} · {adjustment.branch?.name||'Sucursal seleccionada'}</p><div className="form-grid"><label>Cantidad (usa negativo para salida)<input name="quantity" type="number" step="0.001" required/></label><label>Motivo<input name="reason" minLength={2} required/></label></div><div className="modal-actions"><button type="button" className="secondary" onClick={()=>setAdjustment(null)}>Cancelar</button><button className="primary" disabled={actionBusy}>Registrar ajuste</button></div></form></div>}
    {closing&&<div className="modal-backdrop"><form className="modal" onSubmit={closeCash}><div className="modal-head"><div><span className="eyebrow">CIERRE DE CAJA</span><h2>{closing.branch?.name||'Sucursal'}</h2></div><button type="button" className="icon-button" onClick={()=>setClosing(null)}><X size={18}/></button></div><div className="form-grid"><label>Efectivo contado<input name="counted" type="number" min="0" step="0.01" required/></label><label className="wide">Observaciones<input name="notes"/></label></div><div className="modal-actions"><button type="button" className="secondary" onClick={()=>setClosing(null)}>Cancelar</button><button className="primary" disabled={actionBusy}>Cerrar caja</button></div></form></div>}
    {saleReturn&&<div className="modal-backdrop"><form className="modal" onSubmit={submitReturn}><div className="modal-head"><div><span className="eyebrow">DEVOLUCIÓN</span><h2>Venta {saleReturn.row.number}</h2></div><button type="button" className="icon-button" onClick={()=>setSaleReturn(null)}><X size={18}/></button></div><label className="return-reason">Motivo<input required minLength={3} value={saleReturn.reason} onChange={e=>setSaleReturn({...saleReturn,reason:e.target.value})}/></label><div className="return-lines">{saleReturn.items.map((item:any,i:number)=><label key={item.id}>{item.product?.name||item.productId}<small>vendido {item.quantity} · disponible para devolución {item.remaining}</small><input type="number" min="0" max={item.remaining} step="0.001" value={item.quantity} onChange={e=>setSaleReturn({...saleReturn,items:saleReturn.items.map((x:any,j:number)=>j===i?{...x,quantity:Math.min(item.remaining,Number(e.target.value)||0)}:x)})}/></label>)}</div><div className="modal-actions"><button type="button" className="secondary" onClick={()=>setSaleReturn(null)}>Cancelar</button><button className="primary" disabled={actionBusy||!saleReturn.items.some((x:any)=>x.quantity>0)}>{actionBusy?'Registrando…':'Registrar devolución'}</button></div></form></div>}
  </section>;
}
function pageLabel(page:string){return ({products:'Productos',inventory:'Inventario',wood:'Maderas',sales:'Ventas',purchases:'Compras',customers:'Clientes',suppliers:'Proveedores',deliveries:'Entregas',branches:'Sucursales',cash:'Caja',expenses:'Gastos',movements:'Movimientos',users:'Usuarios',audit:'Auditoría',reports:'Reportes',transfers:'Traslados'} as Record<string,string>)[page]||page}
function editFields(page:string,row:any):[string,string,string?][]{const fields:Record<string,[string,string,string?][]>={products:[['name','Producto'],['description','Descripción'],['salePrice','Precio de venta','number'],['purchasePrice','Precio de compra','number'],['wholesalePrice','Precio mayorista','number'],['minStock','Stock mínimo','number']],customers:[['name','Nombre'],['company','Empresa'],['nit','NIT'],['phone','Teléfono'],['email','Correo','email'],['address','Dirección']],suppliers:[['name','Proveedor'],['company','Empresa'],['nit','NIT'],['phone','Teléfono'],['email','Correo','email'],['address','Dirección']],branches:[['name','Sucursal'],['address','Dirección'],['phone','Teléfono']],drivers:[['phone','Teléfono'],['dpi','DPI'],['licenseType','Tipo de licencia'],['licenseNumber','Número de licencia'],['vehicleType','Tipo de vehículo'],['plate','Placa'],['notes','Observaciones']]};if(page==='users')return [['name','Nombre'],['email','Correo','email']];return fields[page]||[['name','Nombre']]}

function SettingsPanel({api,company,setCompany,setError,setSuccess}:any){async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget).entries());try{const updated=await api('/settings',{method:'PATCH',body:JSON.stringify(data)});setCompany(updated);setSuccess('Configuración de empresa guardada.')}catch(e:any){setError(e.message)}}return <form key={company?.updatedAt||company?.name||'settings'} className="panel table-panel settings-form" onSubmit={save}><div className="table-toolbar"><div><h3>Datos de la empresa</h3><p>Estos datos se usan en reportes y comprobantes.</p></div></div><div className="form-grid"><label>Nombre de la empresa<input name="name" defaultValue={company?.name||''} required minLength={2}/></label><label>NIT<input name="nit" defaultValue={company?.nit||''}/></label><label>Teléfono<input name="phone" defaultValue={company?.phone||''}/></label><label>Correo electrónico<input name="email" type="email" defaultValue={company?.email||''}/></label><label className="wide">Dirección<input name="address" defaultValue={company?.address||''}/></label><label>Moneda<select name="currency" defaultValue={company?.currency||'GTQ'}><option value="GTQ">Quetzales (GTQ)</option><option value="USD">Dólares (USD)</option></select></label><label>Impuesto (%)<input name="taxRate" type="number" min="0" max="100" step="0.01" defaultValue={company?.taxRate??12}/></label></div><div className="modal-actions"><button className="primary" type="submit">Guardar configuración</button></div></form>}

function BackupTools({api,rows,onRefresh,setError,setSuccess}:any){return <section className="panel table-panel"><div className="table-toolbar"><div><h3>Respaldos de base de datos</h3><p>{rows.length} archivos disponibles</p></div><button className="primary" onClick={async()=>{try{const x=await api('/backups',{method:'POST'});setSuccess(x.message);onRefresh()}catch(e:any){setError(e.message)}}}><Activity size={15}/>Crear respaldo</button></div><div className="table-scroll"><table><thead><tr><th>Archivo</th><th>Tamaño</th><th>Fecha</th><th>Acción</th></tr></thead><tbody>{rows.map((r:any)=><tr key={r.name}><td>{r.name}</td><td>{(r.size/1048576).toFixed(2)} MB</td><td>{new Date(r.createdAt).toLocaleString('es-GT')}</td><td><button className="secondary" onClick={async()=>{try{const response=await fetch(`/api/backups/${encodeURIComponent(r.name)}/download`,{headers:{Authorization:`Bearer ${localStorage.getItem('erp-token')||''}`}});if(!response.ok)throw new Error('No se pudo descargar el respaldo.');const blob=await response.blob();const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=r.name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(e:any){setError(e.message)}}}><Download size={14}/>Descargar</button></td></tr>)}</tbody></table>{!rows.length&&<div className="empty-state"><div><Activity size={22}/></div><b>Aún no hay respaldos</b><span>Crea un archivo cuando lo necesites.</span></div>}</div></section>}
