import 'dotenv/config';
import bcrypt from 'bcryptjs';
import { PrismaClient } from '@prisma/client';
const prisma=new PrismaClient();
const permissions=['branches.create','branches.view','products.view','products.create','products.edit','inventory.view','inventory.adjust','sales.view','sales.create','purchases.view','purchases.create','customers.view','customers.create','suppliers.view','suppliers.create','users.view','users.create','deliveries.create','reports.view','audit.view','settings.view','settings.edit'];
async function main(){
 for(const key of ['ADMIN','SUCURSAL','CAMIONERO'] as const)await prisma.role.upsert({where:{key},create:{key,name:key==='ADMIN'?'Administrador':key==='SUCURSAL'?'Sucursal':'Camionero'},update:{}});
 const admin=await prisma.role.findUniqueOrThrow({where:{key:'ADMIN'}});const branchRole=await prisma.role.findUniqueOrThrow({where:{key:'SUCURSAL'}});const driverRole=await prisma.role.findUniqueOrThrow({where:{key:'CAMIONERO'}});
 const all=await Promise.all(permissions.map(key=>prisma.permission.upsert({where:{key},create:{key,description:key},update:{}})));
 for(const permission of all)await prisma.rolePermission.upsert({where:{roleId_permissionId:{roleId:admin.id,permissionId:permission.id}},create:{roleId:admin.id,permissionId:permission.id},update:{}});
 for(const key of ['products.view','inventory.view','inventory.adjust','sales.view','sales.create','purchases.view','customers.view','customers.create','suppliers.view','deliveries.create']){const permission=all.find(p=>p.key===key)!;await prisma.rolePermission.upsert({where:{roleId_permissionId:{roleId:branchRole.id,permissionId:permission.id}},create:{roleId:branchRole.id,permissionId:permission.id},update:{}});}
 const b1=await prisma.branch.upsert({where:{code:'T1'},create:{code:'T1',name:'Tienda 1'},update:{}});const b2=await prisma.branch.upsert({where:{code:'T2'},create:{code:'T2',name:'Tienda 2'},update:{}});
 const initialPassword=process.env.SEED_PASSWORD||(process.env.NODE_ENV==='production'?undefined:'Cambiar123!');
 if(!initialPassword)throw new Error('Configura SEED_PASSWORD para crear las cuentas iniciales en producción.');
 if(process.env.NODE_ENV==='production'&&initialPassword.length<12)throw new Error('SEED_PASSWORD debe tener al menos 12 caracteres en producción.');
 const hash=await bcrypt.hash(initialPassword,12);
 await prisma.user.upsert({where:{username:'admin'},create:{username:'admin',email:'admin@ferreteria.local',name:'Administrador General',passwordHash:hash,roleId:admin.id,mustChangePassword:true},update:{}});
 for(const [username,name,branchId] of [['tienda1','Encargado Tienda 1',b1.id],['tienda2','Encargado Tienda 2',b2.id]])await prisma.user.upsert({where:{username},create:{username,name,passwordHash:hash,roleId:branchRole.id,branchId,mustChangePassword:true},update:{}});
 for(const [username,name,phone,plate] of [['camionero1','Camionero 1','5556-1001','P-100ABC'],['camionero2','Camionero 2','5556-1002','P-200DEF']]){const user=await prisma.user.upsert({where:{username},create:{username,name,passwordHash:hash,roleId:driverRole.id,mustChangePassword:true},update:{}});await prisma.driver.upsert({where:{userId:user.id},create:{userId:user.id,phone,vehicleType:'Camión',plate},update:{}});}
 const categories=['Cemento','Hierro','Herramientas','Pintura','Electricidad','Plomería','Maderas','Construcción','Tornillería','Otros'];for(const name of categories)await prisma.category.upsert({where:{name},create:{name},update:{}});
 const seeds=[['CEM-001','Cemento gris 42.5 kg','Cemento',83,98,12],['HIE-001','Hierro corrugado 3/8','Hierro',35,48,75],['HIE-002','Hierro corrugado 1/2','Hierro',58,75,40],['HER-001','Martillo de uña 16 oz','Herramientas',38,55,18],['PIN-001','Pintura látex blanca galón','Pintura',92,135,10],['ELE-001','Cable eléctrico THHN 12 AWG','Electricidad',2.8,4.5,300],['PLO-001','Tubo PVC 1/2 pulgada','Plomería',16,25,62],['TOR-001','Tornillo punta broca caja','Tornillería',24,38,30],['CON-001','Block estándar 15 cm','Construcción',4.5,6.5,500],['MAD-001','Tabla pino 2x4 de 12 pies','Maderas',48,70,80],['MAD-002','Costanera pino 2x3 de 12 pies','Maderas',38,56,55],['HER-002','Alicate universal 8 pulgadas','Herramientas',32,49,15],['PIN-002','Brocha 3 pulgadas','Pintura',12,20,22],['PLO-002','Codo PVC 1/2 pulgada','Plomería',1.8,3.5,120],['ELE-002','Tomacorriente doble','Electricidad',12,21,26]] as const;
 const woods=await prisma.category.findUniqueOrThrow({where:{name:'Maderas'}});
 for(const [sku,name,cat,buy,sell,stock] of seeds){const category=await prisma.category.findUniqueOrThrow({where:{name:cat}});const p=await prisma.product.upsert({where:{sku},create:{sku,name,categoryId:category.id,purchasePrice:buy,salePrice:sell,minStock:10,unit:'unidad'},update:{}});for(const branchId of [b1.id,b2.id])await prisma.inventory.upsert({where:{productId_branchId:{productId:p.id,branchId}},create:{productId:p.id,branchId,quantity:Math.round(stock*(branchId===b1.id?1:.58))},update:{}});if(cat==='Maderas')await prisma.woodProduct.upsert({where:{productId:p.id},create:{productId:p.id,woodType:'Pino',dimensions:name.includes('Tabla')?'2x4':'2x3',length:12,observations:'Madera secada al aire'},update:{}});}
 const customers=[['Constructora El Roble','5551-1020'],['María López','5552-2030'],['Carlos Méndez','5553-3040'],['Proyectos del Valle','5554-4050'],['José Ramírez','5555-5060']];for(const [name,phone] of customers)if(!(await prisma.customer.findFirst({where:{name}})))await prisma.customer.create({data:{name,phone,department:'Guatemala',municipality:'Guatemala'}});
 const suppliers=[['Distribuidora Nacional','2380-1000'],['Materiales La Unión','2380-2000'],['Maderas del Norte','2380-3000'],['Pinturas Centroamericanas','2380-4000'],['Herramientas GT','2380-5000']];for(const [name,phone] of suppliers)if(!(await prisma.supplier.findFirst({where:{name}})))await prisma.supplier.create({data:{name,phone}});
 await prisma.companySettings.upsert({where:{id:'default'},create:{id:'default',name:'Ferretería Central',currency:'GTQ',taxRate:12},update:{}});
 console.log('Seed listo. Usuarios: admin, tienda1, tienda2, camionero1 y camionero2. Contraseña inicial: Cambiar123!');
}
main().finally(()=>prisma.$disconnect());
