import { Router } from 'express';
import { z } from 'zod';
import { prisma } from '../lib/prisma';
import { allow, scopeBranch } from '../middleware/auth';
const r=Router();
const pageArgs = (req:any) => ({ skip: Math.max(0, (Number(req.query.page || 1)-1)*Number(req.query.limit || 20)), take: Math.min(100, Number(req.query.limit || 20)) });
const audit = async (userId:string, action:string, module:string, recordId?:string, details?:any) => prisma.auditLog.create({ data:{ userId, action, module, recordId, details } });

r.get('/branches', async (req,res)=>res.json(await prisma.branch.findMany({where:req.user!.role==='ADMIN'?undefined:{id:req.user!.branchId||'__none__'},orderBy:{name:'asc'}})));
r.post('/branches',allow('branches.create'),async(req,res)=>{const d=z.object({name:z.string().min(2),code:z.string().min(1),address:z.string().optional(),phone:z.string().optional()}).parse(req.body);const b=await prisma.branch.create({data:d});await audit(req.user!.id,'CREAR','branches',b.id);res.status(201).json(b);});
r.patch('/branches/:id',allow('branches.edit'),async(req,res)=>{const d=z.object({name:z.string().min(2).optional(),address:z.string().optional(),phone:z.string().optional(),active:z.boolean().optional()}).parse(req.body);const row=await prisma.branch.update({where:{id:String(req.params.id)},data:d});await audit(req.user!.id,'MODIFICAR','branches',row.id,d);res.json(row);});
r.get('/products',async(req,res)=>{const q=String(req.query.q||'');const branchId=scopeBranch(req);const where:any={active:true,...(q?{OR:[{name:{contains:q,mode:'insensitive'}},{sku:{contains:q,mode:'insensitive'}},{barcode:{contains:q}}]}:{})};const [rows,total]=await Promise.all([prisma.product.findMany({where,...pageArgs(req),orderBy:{name:'asc'},include:{category:true,supplier:true,inventory:{where:branchId?{branchId}:undefined,include:{branch:true}}}}),prisma.product.count({where})]);res.json({data:rows,total});});
r.post('/products',allow('products.create'),async(req,res)=>{const d=z.object({sku:z.string().min(1),name:z.string().min(1),barcode:z.string().optional(),description:z.string().optional(),categoryId:z.string().optional(),supplierId:z.string().optional(),brand:z.string().optional(),unit:z.string().default('unidad'),purchasePrice:z.coerce.number().min(0),salePrice:z.coerce.number().min(0),wholesalePrice:z.coerce.number().min(0).default(0),minStock:z.coerce.number().min(0).default(0),branchId:z.string().optional(),initialStock:z.coerce.number().min(0).default(0)}).parse(req.body);if(req.user!.role!=='ADMIN'&&d.branchId&&d.branchId!==req.user!.branchId)return res.status(403).json({message:'No puedes crear existencias para otra sucursal.'});const branchId=req.user!.role==='ADMIN'?(d.branchId||req.user!.branchId):req.user!.branchId;if(d.initialStock>0&&!branchId)return res.status(400).json({message:'Selecciona la sucursal para las existencias iniciales.'});const p=await prisma.$transaction(async tx=>{const item=await tx.product.create({data:{sku:d.sku,name:d.name,barcode:d.barcode||null,description:d.description,categoryId:d.categoryId||null,supplierId:d.supplierId||null,brand:d.brand,unit:d.unit,purchasePrice:d.purchasePrice,salePrice:d.salePrice,wholesalePrice:d.wholesalePrice,minStock:d.minStock}});if(branchId&&d.initialStock>0){await tx.inventory.create({data:{productId:item.id,branchId,quantity:d.initialStock}});await tx.inventoryMovement.create({data:{productId:item.id,branchId,userId:req.user!.id,type:'ENTRADA',quantity:d.initialStock,reason:'Inventario inicial'}});}return item;});await audit(req.user!.id,'CREAR','products',p.id);res.status(201).json(p);});
r.patch('/products/:id',allow('products.edit'),async(req,res)=>{const d=z.object({name:z.string().min(1).optional(),description:z.string().optional(),categoryId:z.string().nullable().optional(),supplierId:z.string().nullable().optional(),salePrice:z.coerce.number().min(0).optional(),purchasePrice:z.coerce.number().min(0).optional(),wholesalePrice:z.coerce.number().min(0).optional(),minStock:z.coerce.number().min(0).optional(),active:z.boolean().optional()}).parse(req.body);const p=await prisma.product.update({where:{id:String(req.params.id)},data:d});await audit(req.user!.id,'MODIFICAR','products',p.id,d);res.json(p);});
r.get('/categories',async(_req,res)=>res.json(await prisma.category.findMany({where:{active:true},orderBy:{name:'asc'}})));
r.post('/categories',allow('products.create'),async(req,res)=>{const d=z.object({name:z.string().min(2)}).parse(req.body);res.status(201).json(await prisma.category.create({data:d}));});
r.get('/inventory',async(req,res)=>{const branchId=scopeBranch(req);const rows=await prisma.inventory.findMany({where:branchId?{branchId}:undefined,include:{product:{include:{category:true}},branch:true},orderBy:{product:{name:'asc'}}});res.json(rows);});
r.post('/inventory/adjust',allow('inventory.adjust'),async(req,res)=>{const d=z.object({productId:z.string(),branchId:z.string().optional(),quantity:z.coerce.number(),reason:z.string().min(2)}).parse(req.body);if(req.user!.role!=='ADMIN'&&d.branchId&&d.branchId!==req.user!.branchId)return res.status(403).json({message:'No puedes ajustar inventario de otra sucursal.'});const branchId=req.user!.role==='ADMIN'?(d.branchId||req.user!.branchId):req.user!.branchId;if(!branchId)throw Object.assign(new Error('Selecciona una sucursal.'),{statusCode:400});const updated=await prisma.$transaction(async tx=>{await tx.inventory.upsert({where:{productId_branchId:{productId:d.productId,branchId}},create:{productId:d.productId,branchId,quantity:0},update:{}});if(d.quantity<0){const changed=await tx.inventory.updateMany({where:{productId:d.productId,branchId,quantity:{gte:Math.abs(d.quantity)}},data:{quantity:{decrement:Math.abs(d.quantity)}}});if(!changed.count)throw Object.assign(new Error('El ajuste dejaría el inventario en negativo.'),{statusCode:400});}else await tx.inventory.update({where:{productId_branchId:{productId:d.productId,branchId}},data:{quantity:{increment:d.quantity}}});await tx.inventoryMovement.create({data:{productId:d.productId,branchId,userId:req.user!.id,type:'AJUSTE',quantity:d.quantity,reason:d.reason}});return tx.inventory.findUniqueOrThrow({where:{productId_branchId:{productId:d.productId,branchId}}});});res.json(updated);});
r.get('/customers',async(req,res)=>{const q=String(req.query.q||'');const where:any=q?{OR:[{name:{contains:q,mode:'insensitive'}},{nit:{contains:q}},{phone:{contains:q}}]}:{};res.json(await prisma.customer.findMany({where,...pageArgs(req),orderBy:{name:'asc'}}));});
r.post('/customers',allow('customers.create'),async(req,res)=>{const d=z.object({name:z.string().min(2),company:z.string().optional(),nit:z.string().optional(),phone:z.string().optional(),whatsapp:z.string().optional(),email:z.string().email().optional().or(z.literal('')),address:z.string().optional(),department:z.string().optional(),municipality:z.string().optional(),reference:z.string().optional(),notes:z.string().optional()}).parse(req.body);const x=await prisma.customer.create({data:{...d,email:d.email||null,nit:d.nit||null}});await audit(req.user!.id,'CREAR','customers',x.id);res.status(201).json(x);});
r.patch('/customers/:id',allow('customers.edit'),async(req,res)=>{const d=z.object({name:z.string().min(2).optional(),company:z.string().optional(),nit:z.string().optional(),phone:z.string().optional(),whatsapp:z.string().optional(),email:z.string().email().optional().or(z.literal('')),address:z.string().optional(),active:z.boolean().optional()}).parse(req.body);const row=await prisma.customer.update({where:{id:String(req.params.id)},data:{...d,email:d.email===''?null:d.email,nit:d.nit===''?null:d.nit}});await audit(req.user!.id,'MODIFICAR','customers',row.id,d);res.json(row);});
r.get('/suppliers',async(req,res)=>res.json(await prisma.supplier.findMany({where:req.query.q?{name:{contains:String(req.query.q),mode:'insensitive'}}:undefined,...pageArgs(req),orderBy:{name:'asc'}})));
r.post('/suppliers',allow('suppliers.create'),async(req,res)=>{const d=z.object({name:z.string().min(2),company:z.string().optional(),nit:z.string().optional(),phone:z.string().optional(),whatsapp:z.string().optional(),email:z.string().optional(),address:z.string().optional(),contact:z.string().optional(),notes:z.string().optional()}).parse(req.body);const x=await prisma.supplier.create({data:{...d,nit:d.nit||null,email:d.email||null}});await audit(req.user!.id,'CREAR','suppliers',x.id);res.status(201).json(x);});
r.patch('/suppliers/:id',allow('suppliers.edit'),async(req,res)=>{const d=z.object({name:z.string().min(2).optional(),company:z.string().optional(),nit:z.string().optional(),phone:z.string().optional(),whatsapp:z.string().optional(),email:z.string().email().optional().or(z.literal('')),address:z.string().optional(),contact:z.string().optional(),active:z.boolean().optional()}).parse(req.body);const row=await prisma.supplier.update({where:{id:String(req.params.id)},data:{...d,email:d.email===''?null:d.email,nit:d.nit===''?null:d.nit}});await audit(req.user!.id,'MODIFICAR','suppliers',row.id,d);res.json(row);});
r.get('/wood',async(req,res)=>res.json(await prisma.woodProduct.findMany({
  where:req.query.q?{OR:[{woodType:{contains:String(req.query.q),mode:'insensitive'}},{product:{name:{contains:String(req.query.q),mode:'insensitive'}}}]}:undefined,
  include:{product:{include:{inventory:{include:{branch:true}}}}}
})));
r.get('/search',async(req,res)=>{const q=String(req.query.q||'');if(q.length<2)return res.json([]);const [products,customers,suppliers,sales]=await Promise.all([prisma.product.findMany({where:{OR:[{name:{contains:q,mode:'insensitive'}},{sku:{contains:q,mode:'insensitive'}}]},take:5,select:{id:true,name:true,sku:true}}),prisma.customer.findMany({where:{name:{contains:q,mode:'insensitive'}},take:5,select:{id:true,name:true}}),prisma.supplier.findMany({where:{name:{contains:q,mode:'insensitive'}},take:5,select:{id:true,name:true}}),prisma.sale.findMany({where:{number:{contains:q,mode:'insensitive'}},take:5,select:{id:true,number:true,total:true}})]);res.json([{kind:'products',items:products},{kind:'customers',items:customers},{kind:'suppliers',items:suppliers},{kind:'sales',items:sales}]);});
export default r;
