import { Router } from 'express';
import { z } from 'zod';
import { prisma } from '../lib/prisma';
import { allow, scopeBranch } from '../middleware/auth';
const r=Router();
const pageArgs = (req:any) => ({ skip: Math.max(0, (Number(req.query.page || 1)-1)*Number(req.query.limit || 20)), take: Math.min(100, Number(req.query.limit || 20)) });
const audit = async (userId:string, action:string, module:string, recordId?:string, details?:any) => prisma.auditLog.create({ data:{ userId, action, module, recordId, details } });

r.get('/movements',async(req,res)=>res.json(await prisma.inventoryMovement.findMany({where:scopeBranch(req)?{branchId:scopeBranch(req)!}:undefined,include:{product:true,branch:true,user:{select:{name:true}}},...pageArgs(req),orderBy:{createdAt:'desc'}})));
r.get('/cash',async(req,res)=>{const branchId=scopeBranch(req);res.json(await prisma.cashRegister.findMany({where:branchId?{branchId}:undefined,include:{branch:true,user:{select:{name:true}},movements:true},orderBy:{openedAt:'desc'},take:50}));});
r.post('/cash/open',async(req,res)=>{const d=z.object({branchId:z.string().optional(),opening:z.coerce.number().min(0)}).parse(req.body);const branchId=req.user!.role==='ADMIN'?(d.branchId||req.user!.branchId):req.user!.branchId;if(!branchId)return res.status(400).json({message:'Elige una sucursal.'});if(req.user!.role!=='ADMIN'&&d.branchId&&d.branchId!==req.user!.branchId)return res.status(403).json({message:'Sin acceso a esa sucursal.'});const existing=await prisma.cashRegister.findFirst({where:{branchId,closedAt:null}});if(existing)return res.status(409).json({message:'Ya existe una caja abierta en esta sucursal.'});res.status(201).json(await prisma.cashRegister.create({data:{branchId,userId:req.user!.id,opening:d.opening}}));});
r.post('/cash/:id/close',async(req,res)=>{const d=z.object({counted:z.coerce.number().min(0),notes:z.string().optional()}).parse(req.body);const c=await prisma.cashRegister.findUniqueOrThrow({where:{id:String(req.params.id)},include:{movements:true}});if(req.user!.role!=='ADMIN'&&c.branchId!==req.user!.branchId)return res.status(403).json({message:'Sin acceso a esta caja.'});if(c.closedAt)return res.status(400).json({message:'La caja ya está cerrada.'});const expected=c.opening+c.movements.filter(m=>m.method==='EFECTIVO').reduce((n,m)=>n+(m.kind==='INGRESO'?Number(m.amount):-Number(m.amount)),0);res.json(await prisma.cashRegister.update({where:{id:c.id},data:{closing:d.counted,expected,difference:d.counted-expected,notes:d.notes,closedAt:new Date()}}));});
r.get('/expenses',async(req,res)=>res.json(await prisma.expense.findMany({where:scopeBranch(req)?{branchId:scopeBranch(req)!}:undefined,...pageArgs(req),orderBy:{createdAt:'desc'}})));
r.post('/expenses',async(req,res)=>{const d=z.object({category:z.string().min(2),description:z.string().min(2),amount:z.coerce.number().positive(),branchId:z.string().optional(),method:z.enum(['EFECTIVO','TARJETA','TRANSFERENCIA']).default('EFECTIVO'),notes:z.string().optional()}).parse(req.body);if(req.user!.role!=='ADMIN'&&d.branchId&&d.branchId!==req.user!.branchId)return res.status(403).json({message:'No puedes registrar gastos en otra sucursal.'});const branchId=req.user!.role==='ADMIN'?(d.branchId||req.user!.branchId):req.user!.branchId;if(!branchId)return res.status(400).json({message:'Elige una sucursal.'});const x=await prisma.expense.create({data:{...d,branchId,userId:req.user!.id}});const reg=await prisma.cashRegister.findFirst({where:{branchId,closedAt:null}});if(reg)await prisma.cashMovement.create({data:{cashRegisterId:reg.id,kind:'EGRESO',amount:d.amount,method:d.method,description:d.description}});await audit(req.user!.id,'CREAR','expenses',x.id);res.status(201).json(x);});
r.get('/reports/summary',allow('reports.view'),async(req,res)=>{const branchId=scopeBranch(req);const where=branchId?{branchId}:{};const [sales,purchases,expenses,receivables,payables,movements]=await Promise.all([prisma.sale.findMany({where,include:{customer:true,branch:true},orderBy:{createdAt:'desc'},take:200}),prisma.purchase.findMany({where,include:{supplier:true,branch:true},orderBy:{createdAt:'desc'},take:200}),prisma.expense.findMany({where,include:{branch:true},orderBy:{createdAt:'desc'},take:200}),prisma.sale.findMany({where:{...where,status:{in:['PENDIENTE','PARCIAL']}},include:{customer:true}}),prisma.purchase.findMany({where:{...where,status:{in:['PENDIENTE','PARCIAL']}},include:{supplier:true}}),prisma.inventoryMovement.findMany({where,include:{product:true,branch:true},orderBy:{createdAt:'desc'},take:200})]);res.json({sales,purchases,expenses,receivables,payables,movements});});
export default r;
