import { Router } from 'express';
import { z } from 'zod';
import bcrypt from 'bcryptjs';
import { prisma } from '../lib/prisma';
import { allow, scopeBranch } from '../middleware/auth';
const r=Router();
const pageArgs = (req:any) => ({ skip: Math.max(0, (Number(req.query.page || 1)-1)*Number(req.query.limit || 20)), take: Math.min(100, Number(req.query.limit || 20)) });
const audit = async (userId:string, action:string, module:string, recordId?:string, details?:any) => prisma.auditLog.create({ data:{ userId, action, module, recordId, details } });

r.get('/users',allow('users.view'),async(req,res)=>res.json(await prisma.user.findMany({where:req.user!.role==='ADMIN'?{}:{branchId:req.user!.branchId},include:{role:true,branch:true},...pageArgs(req),orderBy:{name:'asc'}}).then(rows=>rows.map(({passwordHash,...u})=>u))));
r.post('/users',allow('users.create'),async(req,res)=>{const d=z.object({username:z.string().min(3),email:z.string().email().optional().or(z.literal('')),name:z.string().min(2),password:z.string().min(10),roleKey:z.enum(['ADMIN','SUCURSAL','CAMIONERO']),branchId:z.string().optional()}).parse(req.body);if(req.user!.role!=='ADMIN'&&d.branchId!==req.user!.branchId) return res.status(403).json({message:'No puedes crear usuarios para otra sucursal.'});const role=await prisma.role.findUniqueOrThrow({where:{key:d.roleKey}});const u=await prisma.user.create({data:{username:d.username,email:d.email||null,name:d.name,passwordHash:await bcrypt.hash(d.password,12),roleId:role.id,branchId:d.branchId||null,mustChangePassword:true}});await audit(req.user!.id,'CREAR','users',u.id);res.status(201).json({id:u.id,username:u.username,name:u.name});});
r.patch('/users/:id',allow('users.edit'),async(req,res)=>{const d=z.object({name:z.string().min(2).optional(),email:z.string().email().optional().or(z.literal('')),active:z.boolean().optional(),password:z.string().min(10).optional()}).parse(req.body);const id=String(req.params.id);if(id===req.user!.id&&d.active===false)return res.status(400).json({message:'No puedes desactivar tu propio usuario.'});const target=await prisma.user.findUniqueOrThrow({where:{id},include:{role:true}});if(req.user!.role!=='ADMIN'&&target.branchId!==req.user!.branchId)return res.status(403).json({message:'No tienes acceso a este usuario.'});if(d.active===false&&target.role.key==='ADMIN'&&await prisma.user.count({where:{active:true,role:{key:'ADMIN'}}})<=1)return res.status(400).json({message:'Debe quedar al menos un administrador activo.'});const row=await prisma.user.update({where:{id},data:{name:d.name,email:d.email===''?null:d.email,active:d.active,...(d.password?{passwordHash:await bcrypt.hash(d.password,12),mustChangePassword:true}:{})},include:{role:true,branch:true}});if(d.active===false||d.password)await prisma.session.updateMany({where:{userId:id,revokedAt:null},data:{revokedAt:new Date()}});await audit(req.user!.id,d.password?'RESTABLECER_CONTRASENA':'MODIFICAR','users',id,{active:d.active});const {passwordHash,...safe}=row;res.json(safe);});
r.get('/drivers',async(_req,res)=>res.json(await prisma.driver.findMany({include:{user:{select:{id:true,name:true,username:true,active:true}}},orderBy:{user:{name:'asc'}}})));
r.post('/drivers',allow('users.create'),async(req,res)=>{const d=z.object({name:z.string().min(2),username:z.string().min(3),password:z.string().min(10),branchId:z.string().optional(),phone:z.string().optional(),dpi:z.string().optional(),licenseType:z.string().optional(),licenseNumber:z.string().optional(),vehicleType:z.string().optional(),plate:z.string().optional(),notes:z.string().optional()}).parse(req.body);const branchId=req.user!.role==='ADMIN'?d.branchId:req.user!.branchId;if(req.user!.role!=='ADMIN'&&d.branchId&&d.branchId!==req.user!.branchId)return res.status(403).json({message:'No puedes crear conductores para otra sucursal.'});const role=await prisma.role.findUniqueOrThrow({where:{key:'CAMIONERO'}});const driver=await prisma.$transaction(async tx=>{const user=await tx.user.create({data:{name:d.name,username:d.username,passwordHash:await bcrypt.hash(d.password,12),roleId:role.id,branchId:branchId||null,mustChangePassword:true}});return tx.driver.create({data:{userId:user.id,phone:d.phone,dpi:d.dpi,licenseType:d.licenseType,licenseNumber:d.licenseNumber,vehicleType:d.vehicleType,plate:d.plate,notes:d.notes},include:{user:{select:{id:true,name:true,username:true}}}});});res.status(201).json(driver);});
r.patch('/drivers/:id',allow('users.edit'),async(req,res)=>{const d=z.object({phone:z.string().optional(),dpi:z.string().optional(),licenseType:z.string().optional(),licenseNumber:z.string().optional(),vehicleType:z.string().optional(),plate:z.string().optional(),notes:z.string().optional(),active:z.boolean().optional()}).parse(req.body);const driver=await prisma.driver.findUniqueOrThrow({where:{id:String(req.params.id)},include:{user:true}});if(req.user!.role!=='ADMIN'&&driver.user.branchId!==req.user!.branchId)return res.status(403).json({message:'No tienes acceso a este camionero.'});const updated=await prisma.$transaction(async tx=>{if(d.active!==undefined)await tx.user.update({where:{id:driver.userId},data:{active:d.active}});return tx.driver.update({where:{id:driver.id},data:{phone:d.phone,dpi:d.dpi,licenseType:d.licenseType,licenseNumber:d.licenseNumber,vehicleType:d.vehicleType,plate:d.plate,notes:d.notes},include:{user:{select:{id:true,name:true,username:true,active:true}}}})});await audit(req.user!.id,'MODIFICAR','drivers',driver.id,d);res.json(updated)});
export default r;
