import { Router } from 'express';
import { z } from 'zod';
import { prisma } from '../lib/prisma';
import { allow, scopeBranch } from '../middleware/auth';
const r=Router();
const pageArgs = (req:any) => ({ skip: Math.max(0, (Number(req.query.page || 1)-1)*Number(req.query.limit || 20)), take: Math.min(100, Number(req.query.limit || 20)) });
const audit = async (userId:string, action:string, module:string, recordId?:string, details?:any) => prisma.auditLog.create({ data:{ userId, action, module, recordId, details } });

r.post('/sales/:id/cancel',allow('sales.cancel'),async(req,res)=>{const d=z.object({reason:z.string().min(3)}).parse(req.body);const id=String(req.params.id);const result=await prisma.$transaction(async tx=>{await tx.$queryRaw`SELECT id FROM "Sale" WHERE id = ${id} FOR UPDATE`;const sale=await tx.sale.findUniqueOrThrow({where:{id},include:{items:true}});if(sale.status==='ANULADA')throw Object.assign(new Error('La venta ya está anulada.'),{statusCode:409});if(req.user!.role!=='ADMIN'&&sale.branchId!==req.user!.branchId)throw Object.assign(new Error('No tienes acceso a esta venta.'),{statusCode:403});for(const line of sale.items){const returned=await tx.saleReturnItem.aggregate({where:{saleItemId:line.id},_sum:{quantity:true}});const restock=Math.max(0,Number(line.quantity)-Number(returned._sum.quantity||0));if(restock){await tx.inventory.upsert({where:{productId_branchId:{productId:line.productId,branchId:sale.branchId}},create:{productId:line.productId,branchId:sale.branchId,quantity:restock},update:{quantity:{increment:restock}}});await tx.inventoryMovement.create({data:{productId:line.productId,branchId:sale.branchId,userId:req.user!.id,type:'DEVOLUCION',quantity:restock,reason:`Anulación ${sale.number}: ${d.reason}`,reference:sale.id}});}}const row=await tx.sale.update({where:{id},data:{status:'ANULADA'}});if(Number(sale.paid)>0){const register=await tx.cashRegister.findFirst({where:{branchId:sale.branchId,closedAt:null}});if(register)await tx.cashMovement.create({data:{cashRegisterId:register.id,kind:'EGRESO',amount:sale.paid,method:sale.paymentMethod==='CREDITO'?'EFECTIVO':sale.paymentMethod,description:`Anulación ${sale.number}`,reference:sale.id}});}return row;});await audit(req.user!.id,'ANULAR','sales',id,{reason:d.reason});res.json(result);});

r.post('/purchases/:id/cancel',allow('purchases.cancel'),async(req,res)=>{const d=z.object({reason:z.string().min(3)}).parse(req.body);const id=String(req.params.id);const result=await prisma.$transaction(async tx=>{await tx.$queryRaw`SELECT id FROM "Purchase" WHERE id = ${id} FOR UPDATE`;const purchase=await tx.purchase.findUniqueOrThrow({where:{id},include:{items:true}});if(purchase.status==='ANULADA')throw Object.assign(new Error('La compra ya está anulada.'),{statusCode:409});if(req.user!.role!=='ADMIN'&&purchase.branchId!==req.user!.branchId)throw Object.assign(new Error('No tienes acceso a esta compra.'),{statusCode:403});for(const line of purchase.items){const changed=await tx.inventory.updateMany({where:{productId:line.productId,branchId:purchase.branchId,quantity:{gte:line.quantity}},data:{quantity:{decrement:line.quantity}}});if(!changed.count)throw Object.assign(new Error('No se puede anular: el stock comprado ya se vendió o trasladó.'),{statusCode:409});await tx.inventoryMovement.create({data:{productId:line.productId,branchId:purchase.branchId,userId:req.user!.id,type:'AJUSTE',quantity:-Number(line.quantity),reason:`Anulación ${purchase.number}: ${d.reason}`,reference:purchase.id}});}const row=await tx.purchase.update({where:{id},data:{status:'ANULADA'}});if(Number(purchase.paid)>0){const register=await tx.cashRegister.findFirst({where:{branchId:purchase.branchId,closedAt:null}});if(register)await tx.cashMovement.create({data:{cashRegisterId:register.id,kind:'INGRESO',amount:purchase.paid,method:purchase.paymentMethod==='CREDITO'?'EFECTIVO':purchase.paymentMethod,description:`Reembolso ${purchase.number}`,reference:purchase.id}});}return row;});await audit(req.user!.id,'ANULAR','purchases',id,{reason:d.reason});res.json(result);});

r.post('/sales/:id/returns',allow('sales.create'),async(req,res)=>{
  const d=z.object({reason:z.string().min(3),items:z.array(z.object({saleItemId:z.string(),quantity:z.coerce.number().positive()})).min(1)}).parse(req.body);
  const saleId=String(req.params.id);
  const returned=await prisma.$transaction(async tx=>{
    await tx.$queryRaw`SELECT id FROM "Sale" WHERE id = ${saleId} FOR UPDATE`;
    const sale=await tx.sale.findUniqueOrThrow({where:{id:saleId},include:{items:true}});
    if(sale.status==='ANULADA')throw Object.assign(new Error('No se puede devolver una venta anulada.'),{statusCode:400});
    if(req.user!.role!=='ADMIN'&&sale.branchId!==req.user!.branchId)throw Object.assign(new Error('No tienes acceso a esta venta.'),{statusCode:403});
    const requested=new Map<string,number>();for(const line of d.items)requested.set(line.saleItemId,(requested.get(line.saleItemId)||0)+line.quantity);
    const priorReturns=await tx.saleReturn.aggregate({where:{saleId},_sum:{total:true}});const originalTotal=Number(sale.total)+Number(priorReturns._sum.total||0);const saleItems=new Map(sale.items.map(x=>[x.id,x]));let total=0;const returnLines:any[]=[];
    for(const [saleItemId,quantity] of requested){const item=saleItems.get(saleItemId);if(!item)throw Object.assign(new Error('El producto no pertenece a esta venta.'),{statusCode:400});const aggregate=await tx.saleReturnItem.aggregate({where:{saleItemId},_sum:{quantity:true}});const previouslyReturned=Number(aggregate._sum.quantity||0);if(previouslyReturned+quantity>Number(item.quantity))throw Object.assign(new Error(`La cantidad devuelta supera lo vendido del producto ${item.productId}.`),{statusCode:400});const amount=Number(item.total)/Number(item.quantity)*quantity*(originalTotal/Math.max(Number(sale.subtotal),0.01));total+=amount;returnLines.push({saleItemId,productId:item.productId,quantity,amount});}
    total=Math.min(total,Number(sale.total));const refund=Math.min(total,Number(sale.paid));
    const record=await tx.saleReturn.create({data:{saleId,userId:req.user!.id,reason:d.reason,total,items:{create:returnLines}},include:{items:true}});
    for(const line of returnLines){await tx.inventory.upsert({where:{productId_branchId:{productId:line.productId,branchId:sale.branchId}},create:{productId:line.productId,branchId:sale.branchId,quantity:line.quantity},update:{quantity:{increment:line.quantity}}});await tx.inventoryMovement.create({data:{productId:line.productId,branchId:sale.branchId,userId:req.user!.id,type:'DEVOLUCION',quantity:line.quantity,reason:`Devolución ${sale.number}: ${d.reason}`,reference:record.id}});}
    const newTotal=Math.max(0,Number(sale.total)-total),newPaid=Math.max(0,Number(sale.paid)-refund);await tx.sale.update({where:{id:sale.id},data:{total:newTotal,paid:newPaid,status:newTotal<=0?'ANULADA':newPaid>=newTotal?'PAGADA':newPaid>0?'PARCIAL':'PENDIENTE'}});
    if(refund>0){const register=await tx.cashRegister.findFirst({where:{branchId:sale.branchId,closedAt:null}});if(register)await tx.cashMovement.create({data:{cashRegisterId:register.id,kind:'EGRESO',amount:refund,method:sale.paymentMethod==='CREDITO'?'EFECTIVO':sale.paymentMethod,description:`Reembolso ${sale.number}`,reference:record.id}});}
    return record;
  });
  await audit(req.user!.id,'DEVOLVER','sales',saleId,{returnId:returned.id,reason:d.reason,total:Number(returned.total)});res.status(201).json(returned);
});

r.get('/sales',async(req,res)=>res.json(await prisma.sale.findMany({where:{...(scopeBranch(req)?{branchId:scopeBranch(req)!}:{}),...(req.query.q?{number:{contains:String(req.query.q),mode:'insensitive'}}:{})},include:{customer:true,user:{select:{name:true}},items:{include:{product:true}},returns:{include:{items:true}}},...pageArgs(req),orderBy:{createdAt:'desc'}})));
r.post('/sales',allow('sales.create'),async(req,res)=>{
  const payment=z.object({amount:z.coerce.number().positive(),method:z.enum(['EFECTIVO','TARJETA','TRANSFERENCIA'])});
  const d=z.object({customerId:z.string().optional(),branchId:z.string().optional(),discount:z.coerce.number().min(0).default(0),taxRate:z.coerce.number().min(0).max(100).optional(),paymentMethod:z.enum(['EFECTIVO','TARJETA','TRANSFERENCIA','CREDITO','MIXTO']),payments:z.array(payment).optional(),dueDate:z.string().optional(),items:z.array(z.object({productId:z.string(),quantity:z.coerce.number().positive(),unitPrice:z.coerce.number().nonnegative().optional()})).min(1)}).parse(req.body);
  const branchId=req.user!.role==='ADMIN'?d.branchId:req.user!.branchId;if(!branchId)throw Object.assign(new Error('Elige una sucursal.'),{statusCode:400});
  const taxRate=d.taxRate??Number((await prisma.companySettings.findUnique({where:{id:'default'}}))?.taxRate||0);
  const sale=await prisma.$transaction(async tx=>{
    let subtotal=0;const lines:any[]=[];
    for(const line of d.items){const p=await tx.product.findUniqueOrThrow({where:{id:line.productId}});const inv=await tx.inventory.findUnique({where:{productId_branchId:{productId:p.id,branchId}}});if(Number(inv?.quantity||0)<line.quantity)throw Object.assign(new Error('Stock insuficiente para '+p.name+'.'),{statusCode:400});const price=line.unitPrice??Number(p.salePrice);subtotal+=price*line.quantity;lines.push({productId:p.id,quantity:line.quantity,unitPrice:price,total:price*line.quantity});}
    if(d.discount>subtotal)throw Object.assign(new Error('El descuento supera el subtotal.'),{statusCode:400});const tax=(subtotal-d.discount)*taxRate/100;const total=subtotal-d.discount+tax;
    const payments=d.paymentMethod==='CREDITO'?[]:d.paymentMethod==='MIXTO'?d.payments||[]:[{amount:total,method:d.paymentMethod}];if(d.paymentMethod==='MIXTO'&&!payments.length)throw Object.assign(new Error('Agrega al menos un método y monto para el pago mixto.'),{statusCode:400});const paid=payments.reduce((n,x)=>n+x.amount,0);if(paid>total+0.005)throw Object.assign(new Error('Los pagos superan el total de la venta.'),{statusCode:400});
    const row=await tx.sale.create({data:{number:'V-'+Date.now(),branchId,customerId:d.customerId||null,userId:req.user!.id,subtotal,discount:d.discount,tax,total,paid,paymentMethod:d.paymentMethod,status:paid>=total?'PAGADA':paid>0?'PARCIAL':'PENDIENTE',dueDate:d.dueDate?new Date(d.dueDate):null,items:{create:lines}}});
    for(const line of lines){const changed=await tx.inventory.updateMany({where:{productId:line.productId,branchId,quantity:{gte:line.quantity}},data:{quantity:{decrement:line.quantity}}});if(!changed.count)throw Object.assign(new Error('Stock insuficiente; actualiza el inventario e intenta nuevamente.'),{statusCode:400});await tx.inventoryMovement.create({data:{productId:line.productId,branchId,userId:req.user!.id,type:'VENTA',quantity:-line.quantity,reason:'Venta '+row.number,reference:row.id}});}
    const register=await tx.cashRegister.findFirst({where:{branchId,closedAt:null}});for(const receipt of payments){await tx.salePayment.create({data:{saleId:row.id,userId:req.user!.id,amount:receipt.amount,method:receipt.method}});if(register)await tx.cashMovement.create({data:{cashRegisterId:register.id,kind:'INGRESO',amount:receipt.amount,method:receipt.method,description:'Venta '+row.number,reference:row.id}});}return row;
  });await audit(req.user!.id,'CREAR','sales',sale.id);res.status(201).json(sale);
});
r.post('/sales/:id/payments',allow('sales.create'),async(req,res)=>{const d=z.object({amount:z.coerce.number().positive(),method:z.enum(['EFECTIVO','TARJETA','TRANSFERENCIA']),note:z.string().optional()}).parse(req.body);const sale=await prisma.$transaction(async tx=>{const s=await tx.sale.findUniqueOrThrow({where:{id:String(req.params.id)}});const balance=Number(s.total)-Number(s.paid);if(d.amount>balance)throw Object.assign(new Error('El abono supera el saldo pendiente.'),{statusCode:400});const paid=Number(s.paid)+d.amount;await tx.salePayment.create({data:{saleId:s.id,userId:req.user!.id,amount:d.amount,method:d.method,note:d.note}});const row=await tx.sale.update({where:{id:s.id},data:{paid,status:paid>=Number(s.total)?'PAGADA':'PARCIAL'}});const register=await tx.cashRegister.findFirst({where:{branchId:s.branchId,closedAt:null}});if(register)await tx.cashMovement.create({data:{cashRegisterId:register.id,kind:'INGRESO',amount:d.amount,method:d.method,description:`Abono ${s.number}`}});return row;});res.json(sale);});
r.post('/purchases/:id/payments',allow('purchases.create'),async(req,res)=>{const d=z.object({amount:z.coerce.number().positive(),method:z.enum(['EFECTIVO','TARJETA','TRANSFERENCIA']),note:z.string().optional()}).parse(req.body);const purchase=await prisma.$transaction(async tx=>{const p=await tx.purchase.findUniqueOrThrow({where:{id:String(req.params.id)}});if(req.user!.role!=='ADMIN'&&p.branchId!==req.user!.branchId)throw Object.assign(new Error('No puedes pagar compras de otra sucursal.'),{statusCode:403});const balance=Number(p.total)-Number(p.paid);if(d.amount>balance)throw Object.assign(new Error('El pago supera el saldo pendiente.'),{statusCode:400});const paid=Number(p.paid)+d.amount;await tx.purchasePayment.create({data:{purchaseId:p.id,userId:req.user!.id,amount:d.amount,method:d.method,note:d.note}});const row=await tx.purchase.update({where:{id:p.id},data:{paid,status:paid>=Number(p.total)?'PAGADA':'PARCIAL'}});const register=await tx.cashRegister.findFirst({where:{branchId:p.branchId,closedAt:null}});if(register)await tx.cashMovement.create({data:{cashRegisterId:register.id,kind:'EGRESO',amount:d.amount,method:d.method,description:`Pago ${p.number}`}});return row;});res.json(purchase);});
r.get('/purchases',async(req,res)=>res.json(await prisma.purchase.findMany({where:scopeBranch(req)?{branchId:scopeBranch(req)!}:undefined,include:{supplier:true,items:{include:{product:true}}},...pageArgs(req),orderBy:{createdAt:'desc'}})));
r.post('/purchases',allow('purchases.create'),async(req,res)=>{
  const payment=z.object({amount:z.coerce.number().positive(),method:z.enum(['EFECTIVO','TARJETA','TRANSFERENCIA'])});
  const d=z.object({supplierId:z.string(),branchId:z.string().optional(),invoiceNumber:z.string().optional(),paymentMethod:z.enum(['EFECTIVO','TARJETA','TRANSFERENCIA','CREDITO','MIXTO']),payments:z.array(payment).optional(),discount:z.coerce.number().min(0).default(0),taxRate:z.coerce.number().min(0).max(100).optional(),items:z.array(z.object({productId:z.string(),quantity:z.coerce.number().positive(),unitCost:z.coerce.number().nonnegative()})).min(1)}).parse(req.body);
  const branchId=req.user!.role==='ADMIN'?d.branchId:req.user!.branchId;if(!branchId)throw Object.assign(new Error('Elige una sucursal.'),{statusCode:400});const taxRate=d.taxRate??Number((await prisma.companySettings.findUnique({where:{id:'default'}}))?.taxRate||0);
  const purchase=await prisma.$transaction(async tx=>{
    const subtotal=d.items.reduce((n,i)=>n+i.quantity*i.unitCost,0);if(d.discount>subtotal)throw Object.assign(new Error('El descuento supera el subtotal.'),{statusCode:400});const tax=(subtotal-d.discount)*taxRate/100;const total=subtotal-d.discount+tax;
    const payments=d.paymentMethod==='CREDITO'?[]:d.paymentMethod==='MIXTO'?d.payments||[]:[{amount:total,method:d.paymentMethod}];if(d.paymentMethod==='MIXTO'&&!payments.length)throw Object.assign(new Error('Agrega al menos un método y monto para el pago mixto.'),{statusCode:400});const paid=payments.reduce((n,x)=>n+x.amount,0);if(paid>total+0.005)throw Object.assign(new Error('Los pagos superan el total de la compra.'),{statusCode:400});
    const row=await tx.purchase.create({data:{number:'C-'+Date.now(),invoiceNumber:d.invoiceNumber,branchId,supplierId:d.supplierId,userId:req.user!.id,subtotal,discount:d.discount,tax,total,paid,paymentMethod:d.paymentMethod,status:paid>=total?'PAGADA':paid>0?'PARCIAL':'PENDIENTE',items:{create:d.items.map(i=>({productId:i.productId,quantity:i.quantity,unitCost:i.unitCost,total:i.quantity*i.unitCost}))}}});
    for(const i of d.items){await tx.inventory.upsert({where:{productId_branchId:{productId:i.productId,branchId}},create:{productId:i.productId,branchId,quantity:i.quantity},update:{quantity:{increment:i.quantity}}});await tx.inventoryMovement.create({data:{productId:i.productId,branchId,userId:req.user!.id,type:'COMPRA',quantity:i.quantity,reason:'Compra '+row.number,reference:row.id}});}
    const register=await tx.cashRegister.findFirst({where:{branchId,closedAt:null}});for(const receipt of payments){await tx.purchasePayment.create({data:{purchaseId:row.id,userId:req.user!.id,amount:receipt.amount,method:receipt.method}});if(register)await tx.cashMovement.create({data:{cashRegisterId:register.id,kind:'EGRESO',amount:receipt.amount,method:receipt.method,description:'Compra '+row.number,reference:row.id}});}return row;
  });await audit(req.user!.id,'CREAR','purchases',purchase.id);res.status(201).json(purchase);
});
r.post('/deliveries',allow('deliveries.create'),async(req,res)=>{const d=z.object({customerId:z.string(),branchId:z.string().optional(),driverId:z.string().optional(),address:z.string().min(5),phone:z.string().optional(),observations:z.string().optional(),scheduledAt:z.string().optional(),items:z.array(z.object({productName:z.string().min(1),quantity:z.coerce.number().positive()})).min(1)}).parse(req.body);const branchId=req.user!.role==='ADMIN'?(d.branchId||req.user!.branchId):req.user!.branchId;if(!branchId)return res.status(400).json({message:'Selecciona una sucursal.'});const row=await prisma.delivery.create({data:{number:`E-${Date.now()}`,customerId:d.customerId,branchId,driverId:d.driverId,address:d.address,phone:d.phone,observations:d.observations,scheduledAt:d.scheduledAt?new Date(d.scheduledAt):undefined,status:d.driverId?'ASIGNADA':'PENDIENTE',items:{create:d.items}}});await audit(req.user!.id,'CREAR','deliveries',row.id);res.status(201).json(row);});
r.get('/routes',async(req,res)=>{const branchId=scopeBranch(req);res.json(await prisma.route.findMany({where:branchId?{deliveries:{some:{branchId}}}:undefined,include:{driver:{include:{user:{select:{name:true}}}},deliveries:{include:{customer:true}}},...pageArgs(req),orderBy:{date:'desc'}}));});
r.post('/routes',allow('deliveries.create'),async(req,res)=>{const d=z.object({name:z.string().min(2),date:z.string(),driverId:z.string().optional().nullable(),observations:z.string().optional(),deliveryIds:z.array(z.string()).min(1)}).parse(req.body);const row=await prisma.$transaction(async tx=>{const deliveries=await tx.delivery.findMany({where:{id:{in:d.deliveryIds}},select:{id:true,branchId:true,status:true}});if(deliveries.length!==new Set(d.deliveryIds).size)throw Object.assign(new Error('Una o más entregas no existen.'),{statusCode:400});if(req.user!.role!=='ADMIN'&&deliveries.some(x=>x.branchId!==req.user!.branchId))throw Object.assign(new Error('No puedes asignar entregas de otra sucursal.'),{statusCode:403});if(deliveries.some(x=>['ENTREGADA','CANCELADA'].includes(x.status)))throw Object.assign(new Error('La ruta no puede incluir entregas ya finalizadas.'),{statusCode:400});const route=await tx.route.create({data:{name:d.name,date:new Date(d.date),driverId:d.driverId||null,observations:d.observations}});await tx.delivery.updateMany({where:{id:{in:d.deliveryIds}},data:{routeId:route.id,driverId:d.driverId||null,status:d.driverId?'ASIGNADA':'PENDIENTE'}});return tx.route.findUniqueOrThrow({where:{id:route.id},include:{driver:{include:{user:{select:{name:true}}}},deliveries:{include:{customer:true}}}});});await audit(req.user!.id,'CREAR','routes',row.id);res.status(201).json(row);});
r.patch('/routes/:id',allow('deliveries.create'),async(req,res)=>{const d=z.object({name:z.string().min(2).optional(),date:z.string().optional(),driverId:z.string().nullable().optional(),observations:z.string().optional(),deliveryIds:z.array(z.string()).optional()}).parse(req.body);const id=String(req.params.id);const row=await prisma.$transaction(async tx=>{const route=await tx.route.findUniqueOrThrow({where:{id},include:{deliveries:true}});if(req.user!.role!=='ADMIN'&&route.deliveries.some(x=>x.branchId!==req.user!.branchId))throw Object.assign(new Error('No tienes acceso a esta ruta.'),{statusCode:403});const assigned=d.deliveryIds?await tx.delivery.findMany({where:{id:{in:d.deliveryIds}},select:{id:true,branchId:true,status:true}}):[];if(d.deliveryIds&&(assigned.length!==new Set(d.deliveryIds).size||assigned.some(x=>['ENTREGADA','CANCELADA'].includes(x.status))))throw Object.assign(new Error('La selección contiene entregas no disponibles.'),{statusCode:400});if(req.user!.role!=='ADMIN'&&assigned.some(x=>x.branchId!==req.user!.branchId))throw Object.assign(new Error('No puedes asignar entregas de otra sucursal.'),{statusCode:403});if(d.deliveryIds){await tx.delivery.updateMany({where:{routeId:id},data:{routeId:null,driverId:null,status:'PENDIENTE'}});await tx.delivery.updateMany({where:{id:{in:d.deliveryIds}},data:{routeId:id,driverId:d.driverId===undefined?route.driverId:d.driverId,status:(d.driverId??route.driverId)?'ASIGNADA':'PENDIENTE'}});}await tx.route.update({where:{id},data:{name:d.name,date:d.date?new Date(d.date):undefined,driverId:d.driverId,observations:d.observations}});return tx.route.findUniqueOrThrow({where:{id},include:{driver:{include:{user:{select:{name:true}}}},deliveries:{include:{customer:true}}}});});await audit(req.user!.id,'MODIFICAR','routes',id);res.json(row);});
r.get('/transfers',async(req,res)=>{const branchId=scopeBranch(req);res.json(await prisma.transfer.findMany({where:branchId?{OR:[{originId:branchId},{destinationId:branchId}]}:undefined,include:{origin:true,destination:true},...pageArgs(req),orderBy:{createdAt:'desc'}}));});
r.post('/transfers',allow('inventory.adjust'),async(req,res)=>{const d=z.object({originId:z.string(),destinationId:z.string(),notes:z.string().optional(),items:z.array(z.object({productId:z.string(),quantity:z.coerce.number().positive()})).min(1)}).parse(req.body);if(d.originId===d.destinationId)return res.status(400).json({message:'El origen y destino deben ser diferentes.'});if(req.user!.role!=='ADMIN'&&d.originId!==req.user!.branchId)return res.status(403).json({message:'Solo puedes trasladar desde tu sucursal.'});const transfer=await prisma.$transaction(async tx=>{for(const i of d.items){const inventory=await tx.inventory.findUnique({where:{productId_branchId:{productId:i.productId,branchId:d.originId}}});if(Number(inventory?.quantity||0)<i.quantity)throw Object.assign(new Error('Stock insuficiente para completar el traslado.'),{statusCode:400});await tx.inventory.update({where:{productId_branchId:{productId:i.productId,branchId:d.originId}},data:{quantity:{decrement:i.quantity}}});await tx.inventoryMovement.create({data:{productId:i.productId,branchId:d.originId,userId:req.user!.id,type:'TRASLADO',quantity:-i.quantity,reason:'Traslado enviado'}});}return tx.transfer.create({data:{number:`T-${Date.now()}`,originId:d.originId,destinationId:d.destinationId,userId:req.user!.id,items:d.items,notes:d.notes,status:'ENVIADO'}});});await audit(req.user!.id,'ENVIAR','transfers',transfer.id);res.status(201).json(transfer);});
r.post('/transfers/:id/receive',allow('inventory.adjust'),async(req,res)=>{const transfer=await prisma.$transaction(async tx=>{const t=await tx.transfer.findUniqueOrThrow({where:{id:String(req.params.id)}});if(req.user!.role!=='ADMIN'&&t.destinationId!==req.user!.branchId)throw Object.assign(new Error('Solo la sucursal destino puede recibir este traslado.'),{statusCode:403});if(t.status!=='ENVIADO')throw Object.assign(new Error('El traslado no está pendiente de recepción.'),{statusCode:400});const items=t.items as {productId:string;quantity:number}[];for(const i of items){await tx.inventory.upsert({where:{productId_branchId:{productId:i.productId,branchId:t.destinationId}},create:{productId:i.productId,branchId:t.destinationId,quantity:i.quantity},update:{quantity:{increment:i.quantity}}});await tx.inventoryMovement.create({data:{productId:i.productId,branchId:t.destinationId,userId:req.user!.id,type:'TRASLADO',quantity:i.quantity,reason:`Recepción ${t.number}`}});}return tx.transfer.update({where:{id:t.id},data:{status:'RECIBIDO',receivedBy:req.user!.id}});});res.json(transfer);});
r.get('/deliveries',async(req,res)=>{const where:any=req.user!.role==='CAMIONERO'?{driverId:req.user!.driverId}:scopeBranch(req)?{branchId:scopeBranch(req)!}:{};res.json(await prisma.delivery.findMany({where,include:{customer:true,driver:{include:{user:{select:{name:true}}}},items:true},...pageArgs(req),orderBy:{createdAt:'desc'}}));});
r.patch('/deliveries/:id/status',async(req,res)=>{const d=z.object({status:z.enum(['EN_CAMINO','ENTREGADA','NO_ENTREGADA','CANCELADA'])}).parse(req.body);const delivery=await prisma.delivery.findUniqueOrThrow({where:{id:String(req.params.id)}});if(req.user!.role==='CAMIONERO'&&delivery.driverId!==req.user!.driverId)return res.status(403).json({message:'Esta entrega no está asignada a tu usuario.'});if(req.user!.role==='CAMIONERO'&&!['ASIGNADA','EN_CAMINO'].includes(delivery.status))return res.status(400).json({message:'No se puede cambiar el estado de esta entrega.'});if(req.user!.role==='SUCURSAL'&&delivery.branchId!==req.user!.branchId)return res.status(403).json({message:'No tienes acceso a entregas de otra sucursal.'});const updated=await prisma.delivery.update({where:{id:delivery.id},data:{status:d.status}});await audit(req.user!.id,'CAMBIAR_ESTADO','deliveries',delivery.id,{status:d.status});res.json(updated);});
export default r;
